### ISSUE TITLE
Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

### ISSUE THREAD

**Issue by gopikrishnangs44** [geoschem/GCClassic#71]
### Your name

Gopikrishnan

### Your affiliation

Columbia University, NY

### Please provide a clear and concise description of your question or discussion topic.

I am running GCClassic version 14.4.3.
Geos Chem runs perfect with the MERRA2 4x5 gridding simulations and I saved the BC to the Outputdirs. 

The error occurs when I try to run the nested version the model. The time stepping begins and the model just stops as TP core. 

```
********************************************
* B e g i n   T i m e   S t e p p i n g !! *
********************************************

---> DATE: 2018/01/01  UTC: 00:00
 HEMCO already called for this timestep. Returning.
 Getting CH4 boundary conditions in GEOS-Chem from :NOAA_GMD_CH4
NASA-GSFC Tracer Transport Module successfully initialized
```

Both my slurm script and the env file has 

```
export OMP_NUM_THREADS=32
export F_UFMTENDIAN=big
export OMP_STACKSIZE=3000m
ulimit -s unlimited
```
 
And these are the memory asked for in the shared system
```
#!/bin/bash
#SBATCH -A fiore         # Account
#SBATCH --job-name=GC_run    # The job name
#SBATCH -c 32                # Number of cores
#SBATCH -N 1                 # Ensure that all cores are on one machine
#SBATCH -t 0-02:00           # Runtime in D-HH:MM
#SBATCH --exclusive           # Memory pool for all cores
#SBATCH -C mem768
#SBATCH --mem=700GB
```

The slurm output is

```
Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:

Backtrace for this error:

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x15555363eb4f in ???
#1  0x5c0baa in tp2d
        at /burg/fiore_new/users/gg2995/test1/gc_05x0625_merra2_fullchem/CodeDir/src/GEOS-Chem/GeosCore/tpcore_window_mod.F90:1471
#0  0x15555363eb4f in ???
#1  0x5c0baa in tp2d
        at /burg/fiore_new/users/gg2995/test1/gc_05x0625_merra2_fullchem/CodeDir/src/GEOS-Chem/GeosCore/tpcore_window_mod.F90:1471
#2  0x5c9711 in __tpcore_window_mod_MOD_air_mass_flux._omp_fn.1
        at /burg/fiore_new/users/gg2995/test1/gc_05x0625_merra2_fullchem/CodeDir/src/GEOS-Chem/GeosCore/tpcore_window_mod.F90:1155
#3  0x15555404f01d in gomp_thread_start
        at /local/gg2995/spack-stage/spack-stage-gcc-10.2.0-ca5qgfppgl4tppua3svba6vehsuvjayp/spack-src/libgomp/team.c:123
#0  0x15555363eb4f in ???
#1  0x5c0baa in tp2d
        at /burg/fiore_new/users/gg2995/test1/gc_05x0625_merra2_fullchem/CodeDir/src/GEOS-Chem/GeosCore/tpcore_window_mod.F90:1471
#2  0x5c9711 in __tpcore_window_mod_MOD_air_mass_flux._omp_fn.1
        at /burg/fiore_new/users/gg2995/test1/gc_05x0625_merra2_fullchem/CodeDir/src/GEOS-Chem/GeosCore/tpcore_window_mod.F90:1155
#3  0x15555404f01d in gomp_thread_start
        at /local/gg2995/spack-stage/spack-stage-gcc-10.2.0-ca5qgfppgl4tppua3svba6vehsuvjayp/spack-src/libgomp/team.c:123
#4  0x1555539bd1c9 in ???
#5  0x155553629e72 in ???
#6  0xffffffffffffffff in ???
real 91.97
user 526.29
sys 15.03
srun: error: g277: task 0: Exited with exit code 139
```

Please see the issue.

**Comment by yantosca** [comment]
I will transfer this issue to the GEOS-Chem "science codebase" repository.  The GCClassic issue tracker is for issues pertaining to the GCClassic wrapper itself.
